###################################################################################
##### 
#####         PRODUKTION, SV-ENTWICKLUNG
#####         VORSICHT! Kodierung: UTF-8 bitte so lassen !!!
#####         !!! "\u" wird falsch interpretiert !!! => Malformed \uxxx Exception
#####
###################################################################################

path.lucyidx       =..\IDX\data\index
path.lucyidx.scan  =..\IDX-SCAN\data\index
path.archivt       =..\..\AEPDIREKT\ARCHIV\DATA

dir.root.scan      =..\..\AEPDIREKT\ARCHIV\SCANS
file.offenescan    =^Halde_DIR.*
file.offenearch    =^Halde_DB.*

file.lueckenprot   =..\..\AEPDIREKT\ARCHIV\TAGESBELEGE\Lückenkontrolle.txt
file.lueckenprot.sr=..\..\AEPDIREKT\ARCHIV\SAMMELRECHNUNGEN\LückenkontrolleSR.txt

file.userdb        =..\..\AEPDIREKT\USER\decoUser.sdb
file.userontime    =..\..\AEPDIREKT\USER\UserOnTime.sdb
path.defekte       =..\..\AEPDIREKT\ARCHIV\LISTEN\01_DEFEKTE.sdb
file.btmdb         =..\..\AEPDIREKT\ARCHIV\LISTEN\02_BTM.sdb
path.reimporte     =..\..\AEPDIREKT\ARCHIV\LISTEN\03_REIMPORTE.sdb
file.transfusion   =..\..\AEPDIREKT\ARCHIV\LISTEN\04_TRANSFUSION.sdb
file.tierarznei    =..\..\AEPDIREKT\ARCHIV\LISTEN\05_TIERARZNEI.sdb
file.hochpreis     =..\..\AEPDIREKT\ARCHIV\LISTEN\06_HOCHPREISER.sdb
file.valuta        =..\..\AEPDIREKT\ARCHIV\LISTEN\07_VALUTA.sdb
file.clubdbbestand =..\..\AEPDIREKT\ARCHIV\LISTEN\08_CLUBBESTAND.sdb
file.clubdbaberkauf=..\..\AEPDIREKT\ARCHIV\LISTEN\09_CLUBVERKAUF.sdb
file.chargendb     =..\..\AEPDIREKT\ARCHIV\LISTEN\10_CHARGEN.sdb
file.ueberweiser   =..\..\AEPDIREKT\ARCHIV\LISTEN\11_UEBERWEISER.sdb