dokumentType           = Dok. Type
lieferantNr            = LieferantenNr
lieferantenname        = LieferantenName
bestellNr              = BestellNr
dokDatum               = Dok. Datum

error.datepattern      = Ungültiges Datum! Erwartetes Format: dd.mm.yyyy
error.notanumber       = Das Feld "Bestellnummer" muss Zahlen enthalten!
error.liefname.exist   = Ungültiger Lieferantenname!
error.liefnr.exist     = Ungültige Lieferantennummer!
error.liefnrname.exist = Ungültige Nummer o. Name :  '${item}' !
