# Standartlogger
log4j.rootLogger=DEBUG, stdout

# Stdout fuer alle
# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[%d{yyyy-MM-dd HH:mm:ss}] %m%n

# Wicket
log4j.logger.org.apache.wicket=INFO
log4j.logger.org.apache.wicket.protocol.http.HttpSessionStore=INFO
log4j.logger.org.apache.wicket.version=INFO
log4j.logger.org.apache.wicket.RequestCycle=INFO

# CONSOLE is set to be a ConsoleAppender using a PatternLayout.
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=[%d{yyyy-MM-dd HH:mm:ss}] %m%n

log4j.category.LOGFILE=DEBUG,LOGFILE,stdout
log4j.additivity.LOGFILE=true
#console erwünscht!
log4j.appender.LOGFILE=org.apache.log4j.ConsoleAppender 
log4j.appender.LOGFILE=org.apache.log4j.DailyRollingFileAppender
log4j.appender.LOGFILE.File=c:/temp/db.log
log4j.appender.LOGFILE.layout=org.apache.log4j.PatternLayout
log4j.appender.LOGFILE.layout.ConversionPattern=[%d{yyyy-MM-dd HH:mm:ss}] %m%n

####################################################################################
##### AEP - Customlogger
###
log4j.category.aepDebugLog=INFO, reportsLog, stdout
log4j.additivity.aepDebugLog=false

#log4j.appender.reportsLog=org.apache.log4j.FileAppender
log4j.appender.reportsLog.Stdout=org.apache.log4j.ConsoleAppender
log4j.appender.reportsLog=org.apache.log4j.DailyRollingFileAppender
log4j.appender.reportsLog.File=aepDebug.log
log4j.appender.reportsLog.layout=org.apache.log4j.PatternLayout
log4j.appender.reportsLog.layout.ConversionPattern=[%d{yyyy-MM-dd HH:mm:ss}][%F:%L]%M - %m%n

# -------------------------
# Logging Level für bestimmte Packages
# -------------------------
log4j.logger.de.decodetron=INFO
