############################################################
##### !!! DB - JUNIT !!!
############################################################
file.db.clubbestand          =..\AEPJUNIT\ClubBestand.sdb
file.db.defekte              =..\AEPJUNIT\DEFEKTE.sdb
file.db.club20131106         =..\AEPJUNIT\CLUB.sdb
file.db.chargen              =..\AEPJUNIT\CHARGEN.sdb
file.db.reimporte            =..\AEPJUNIT\REIMPORTE.sdb
file.db.user                 =..\AEPJUNIT\decoUser.sdb
file.db.btm                  =..\AEPJUNIT\BTM.sdb
file.db.hochpreiser          =..\AEPJUNIT\HOCHPREISER.sdb
file.db.tierarznei           =..\AEPJUNIT\TIERARZNEI.sdb
file.db.historybr.ju         =..\AEPJUNIT\historybr.sdb
file.db.userstatistik        =..\AEPJUNIT\UserOnTime.sdb

path.halde.pdf.ju            =..\AEPJUNIT\SCANS\HALDE
path.halde.bsatz.save.ju     =..\AEPJUNIT\SCANS\SAVE
path.halde.bsatz.tmp.save.ju =..\AEPJUNIT\SCANS\TMP
path.halde.lieferini.ju      =..\AEPJUNIT\SCANS\Lieferanten.ini

############################################################
##### !!! LUCENE - JUNIT !!!
############################################################
file.solr.rech       =..\AEPJUNIT\IDX\data\index
file.solr.rechscan   =..\AEPJUNIT\IDX-SCAN\data\index

############################################################
##### !!! DB - PRODUKTION u. JUNIT!!!
############################################################
file.db.historybr    =..\..\..\AEPDIREKT\USER\historybr.sdb

############################################################
##### HALDE - PFADANGABEN
############################################################
path.halde.lieferini      =..\..\..\AEPDIREKT\ARCHIV\Stammdaten\Lieferanten.ini
path.halde.scan.pdf       =..\..\..\AEPDIREKT\ARCHIV\SCANS\HALDE
path.halde.scan.bsatz.save=..\..\..\AEPDIREKT\AKTUELL\Self-Service

############################################################
##### LUECKENPROTOKOLLE 
##### Normalerweise müssten alle DB-Informationen hier liegen!
##### Jetzt also zum 1. mal richtig gemacht ...
############################################################
file.db.sr.lue.in        = ..\..\..\AEPDIREKT\ARCHIV\SAMMELRECHNUNGEN\SAMMELRECHNUNGEN.sdb
file.db.sr.lue.out       = ..\..\..\AEPDIREKT\ARCHIV\SAMMELRECHNUNGEN\LückenkontrolleSR.txt

############################################################
##### Spaltenbezeichnungen
###
table.row1=id
table.row2=vorname
table.row3=nachname
table.row4=login
table.row5=passwd
table.row6=anlagedatum
table.row7=Filter
table.row8=GroupId