###############################################
##### Textfelder                           ####
###############################################
label.TagesDatum         = Tagesdatum
label.AuftragDatum       = Lieferdatum

label.TagesDatumVon      = Tagesdatum von
label.TagesDatumBis      = Tagesdatum bis

label.AuftragDatumVon    = Lieferdatum von
label.AuftragDatumBis    = Lieferdatum bis

label.KundenNr           = Kundennummer
label.AuftragsNr         = Auftragsnummer
label.Chargennummer      = Chargennummer
label.PicklistenNr       = Picklistennummer
label.LieferantNr        = Lieferantennummer
label.LieferscheinNr     = Lieferscheinnummer

label.Ort                = Ort
label.Plz                = Plz
label.Strasse            = Straﬂe
label.InhaberName        = Inhabername 
label.Apothekenname      = Apothekenname
label.LieferantName      = Lieferantenname
label.Artikelbezeichnung = Artikelbezeichnung

label.PZN                = PZN
label.Menge              = Menge
label.Preis              = Preis
label.Betrag             = Betrag
label.ClubKz             = ClubKz
label.Bestand            = Bestand
label.Original_AEP       = Orig. AEP
label.Orig_AEP_BET       = Orig. AEP Betrag
label.Defektengrund      = Defektengrund 
label.Faelligkeit        = F‰lligkeit

###############################################
##### Tabellen                             ####
###############################################

labeltable.TagesDatum         = Tages-<br>datum
labeltable.AuftragDatum       = Liefer-<br>Datum

labeltable.KundenNr           = Kunden-<br>nummer
labeltable.AuftragsNr         = Auftrags-<br>nummer
labeltable.Chargennummer      = Chargen-<br>nummer
labeltable.PicklistenNr       = Picklisten-<br>nummer
labeltable.LieferantNr        = Lieferanten-<br>nummer
labeltable.LieferscheinNr     = Lieferschein-<br>nummer

labeltable.Ort                = Ort
labeltable.Plz                = Plz
labeltable.Strasse            = Straﬂe
labeltable.InhaberName        = Inhaber-<br>name 
labeltable.Apothekenname      = Apotheken-<br>name
labeltable.LieferantName      = Lieferanten-<br>name
labeltable.Artikelbezeichnung = Artikel-<br>bezeichnung

labeltable.PZN                = PZN
labeltable.Menge              = Menge
labeltable.Preis              = Preis
labeltable.Betrag             = Betrag
labeltable.ClubKz             = ClubKz
labeltable.Bestand            = Bestand
labeltable.Original_AEP       = Original AEP
labeltable.Orig_AEP_BET       = Original-<br>AEP Betrag
labeltable.Defektengrund      = Defektengrund 
labeltable.Faelligkeit        = F‰lligkeit

###############################################
##### PDFs                                 ####
###############################################
labeltablepdf.TagesDatum         = Tages-\nDatum
labeltablepdf.AuftragDatum       = Liefer-\nDatum

labeltablepdf.KundenNr           = Kunden-\nnummer
labeltablepdf.AuftragsNr         = Auftrags-\nnummer
labeltablepdf.Chargennummer      = Chargen-\nnummer
labeltablepdf.PicklistenNr       = Picklisten-\nnummer
labeltablepdf.LieferantNr        = Lieferanten-\nnummer
labeltablepdf.LieferscheinNr     = Lieferschein-\nnummer

labeltablepdf.Ort                = Ort
labeltablepdf.Plz                = Plz
labeltablepdf.Straﬂe             = Straﬂze
labeltablepdf.InhaberName        = Inhabername 
labeltablepdf.Apothekenname      = Apothekenname
labeltablepdf.LieferantName      = Lieferantenname
labeltablepdf.Artikelbezeichnung = Artikelbezeichnung

labeltablepdf.PZN                = PZN
labeltablepdf.Menge              = Menge
labeltablepdf.Preis              = Preis
labeltablepdf.Betrag             = Betrag
labeltablepdf.ClubKz             = ClubKz
labeltablepdf.Bestand            = Bestand
labeltablepdf.Original_AEP       = Original AEP
labeltablepdf.Orig_AEP_BET       = Original-\nAEP Betrag
labeltablepdf.Defektengrund      = Defektengrund 
labeltablepdf.Faelligkeit        = F‰lligkeit

###############################################
##### extra-Label f. Table ?              #####
###############################################
label.BenLogin                = Login