label.vorname                = Vorname
label.nachname               = Nachname
label.login                  = Login
label.passwd                 = Passwort
label.anlagedatum            = Anlagedatum
label.Filter                 = Filter
label.GroupIds               = GruppenIds
label.Vertriebsleitung       = Vertriebsleitung
label.Gebiet                 = Gebiet
label.pwdreset				 = Passwort-\nreset
label.deleteUser             = Benutzer-\nlöschen
label.changeUser             = Benutzer-\nändern
#label.knr = BLAH

###################################################

#label.verver                 = Defekte
#label.btm                    = BTM
#label.reimp                  = Reimport
#label.tfg                    = Chargen\ndoku
#label.tierarz                = Tier\narznei
#
#label.hochpr                 = Hoch\npreis
#label.valuta                 = Valuta
#label.clubbestand            = Club\nbestand
#label.clubabver              = Club\naberk
#label.chargen                = Chargen
#
#label.uebe                   = Ãœber\nweiser
#label.ls                     = Liefer\nscheine
#label.nb                     = Nachbe\nlastungen
#label.gs                     = Gutschriften
#label.ek                     = Einkaufs\nauftrÃ¤ge
#
#label.sr                     = Sammel\nrechnungen
#label.sclf                   = Scan-\nLieferscheine
#label.scrg                   = Scan-\nRechnungen
#label.scrt                   = Scan-\nRetouren
#label.scsd                   = Scane-\nSonstige
#
#label.pwz                    = Passwort\nzurÃ¼cksetzen
#label.ververl                = Defekte-\nLieferanten
#label.bea                    = Benutzer\nbearbeiten (Int.)
#label.brv                    = Rechte\nverwalten

#label.verver                 = 1_01
#label.btm                    = 1_02
#label.reimp                  = 1_03
#label.tfg                    = 1_04
#label.tierarz                = 1_05
#
#label.hochpr                 = 1_06
#label.valuta                 = 1_07
#label.clubbestand            = 1_08
#label.clubabver             = 1_09
#label.chargen                = 1_10
#
#label.uebe                   = 1_11
#label.ls                     = 2_01
#label.nb                     = 2_02
#label.gs                     = 2_03
#label.ek                     = 2_04
#
#label.sr                     = 2_05
#label.sclf                   = 3_01
#label.scrg                   = 3_02
#label.scrt                   = 3_03
#label.scsd                   = 3_04
#
#label.pwz                    = Pwd
#label.ververl                = 1_01L
#label.bea                    = BBe
#label.brv                    = BRe


label.verver                 = Defekte
label.btm                    = BTM
label.reimp                  = Reimport
label.tfg                    = Chargendoku
label.tierarz                = Tierarznei

label.hochpr                 = Hochpreis
label.valuta                 = Valuta
label.clubbestand            = Clubbestand
label.clubabver              = Clubaberk
label.chargen                = Chargen

label.uebe                   = Überweiser
label.ls                     = Lieferscheine
label.nb                     = Nachbelastungen
label.gs                     = Gutschriften
label.ek                     = Einkaufsaufträge

label.sr                     = Sammelrechnungen
label.sclf                   = Scan-Lieferscheine
label.scrg                   = Scan-Rechnungen
label.scrt                   = Scan-Retouren
label.scsd                   = Scane-Sonstige

label.pwz                    = Passwort zurückset.
label.ververl                = Defekte-Lieferanten
label.bea                    = Benutzer bearbeiten
label.brv                    = Rechte verwalten
label.has                    = Haldenstatus
label.bes                    = Benutzerstatus



ben.filter.error.superuser   = Das Feld 'Filter' entspricht nicht dem erwarteten Muster: <br\> [Wort], [Wort], [*], ...
ben.filter.error.adminuser   = Das Feld 'Filter' entspricht nicht dem erwarteten Muster: <br\> [Wort], [Wort],  ...
ben.login.exist              = Das Login existiert bereits! Siehe Benutzer: "${vorname}, ${nachname}".
ben.mm.group.empty           = Bitte wählen Sie eine Gruppe aus!
PasswordChange.pwdchange.error = Bitte ändern Sie Ihr Passwort.<br\> Das Standardpasswort ist nicht erlaubt!